OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer
        SANS:
          - "localhost"

PeerOrgs:
  - Name: Org1
    Domain: org1.example.com
    CA:
       Hostname: ca # implicitly ca.org1.example.com
    Template:
      Count: 2
      SANS:
        - "localhost"
      
    Users:
      Count: 1

  - Name: Org2
    Domain: org2.example.com
    CA:
       Hostname: ca # implicitly ca.org1.example.com

    Template:
      Count: 2
      SANS:
        - "localhost"
    Users:
      Count: 1
