apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabric-peer2
spec:
  selector:
    matchLabels:
      app: fabric-peer2
  replicas: 1
  template:
    metadata:
      labels:
        app: fabric-peer2
    spec:
      containers:
      - name: fabric-peer2
        image: hyperledger/fabric-peer:2.2
        workingDir: /user/local/bin
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: portpeer1
          containerPort: 9051
        - name: portpeer2
          containerPort: 19051
        env:
        #Generic peer variables
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE
          value: fabric_test
        - name: FABRIC_LOGGING_SPEC
          value: INFO
        # value: DEBUG
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_PROFILE_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_CERT_FILE
          value: /etc/hyperledger/fabric/tls/server.crt
        - name: CORE_PEER_TLS_KEY_FILE
          value: /etc/hyperledger/fabric/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /etc/hyperledger/fabric/tls/ca.crt
        # Peer specific variabes
        - name: CORE_PEER_ID
          value: peer1.org1.example.com
        - name: CORE_PEER_ADDRESS
          value: peer1.org1.example.com:7051
        - name: CORE_PEER_LISTENADDRESS
          value: 0.0.0.0:7051
        - name: CORE_PEER_CHAINCODEADDRESS
          value: peer1.org1.example.com:7052
        - name: CORE_PEER_CHAINCODELISTENADDRESS
          value: 0.0.0.0:7052
        - name: CORE_PEER_GOSSIP_BOOTSTRAP
          value: peer1.org1.example.com:7051
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: peer1.org1.example.com:7051
        - name: CORE_PEER_LOCALMSPID
          value: Org1MSP
        - name: CORE_OPERATIONS_LISTENADDRESS
          value: 0.0.0.0:17051
        # command: ["sleep", "30000"]
        volumeMounts:
          - name: dockersocket
            mountPath: /host/var/run/docker.sock
          - name: peer1-msp
            mountPath: /etc/hyperledger/fabric/msp
          - name: peer1-tls
            mountPath: /etc/hyperledger/fabric/tls
            
      volumes:
        - name: dockersocket
          hostPath:
            path: /var/run/docker.sock
        - name: peer1-msp
          hostPath:
            path: /Users/jongyoungcha/gowork/fabric-kubernetes-tutorial/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp
            type: DirectoryOrCreate
        - name: peer1-tls
          hostPath:
            path: /Users/jongyoungcha/gowork/fabric-kubernetes-tutorial/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls
            type: DirectoryOrCreate
        # - name: peer1-domain
        # hostPath:
          # path: peer0.org1.example.com:/var/hyperledger/production
          # type: DirectoryOrCreate
