apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabric-orderer
spec:
  selector:
    matchLabels:
      app: fabric-orderer
  replicas: 1
  template:
    metadata:
      labels:
        app: fabric-orderer
    spec:
      containers:
      - name: fabric-orderer
        image: hyperledger/fabric-orderer:2.2
        ports:
        - containerPort: 80
        env:
        - name: ORDERER_GENERAL_LISTENADDRESS
          value: 0.0.0.0
        - name: ORDERER_GENERAL_LISTENPORT
          value: "7050"
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: file
        - name: ORDERER_GENERAL_GENESISFILE
          value: /var/hyperledger/orderer/orderer.genesis.block
        - name: ORDERER_GENERAL_LOCALMSPID
          value: OrdererMSP
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: /var/hyperledger/orderer/msp
        - name: ORDERER_OPERATIONS_LISTENADDRESS
          value: 0.0.0.0:17050
