#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: block-pv
spec:
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Mi
  hostPath:
    path: /Users/jongyoungcha/gowork/fabric-kubernetes-tutorial/system-genesis-block
    type: Directory
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: orderer-msp-pv
spec:
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Mi
  hostPath:
    path: /Users/jongyoungcha/gowork/fabric-kubernetes-tutorial/crypto-config/ordererOrganizations/example.com/msp
    type: Directory


---
# - name: volumes-share
#   hostPath:
#     path: /Users/jongyoungcha/volumes/share
#     type: DirectoryOrCreate
# - name: volumes-block
#   hostPath:
#     path: /Users/jongyoungcha/volumes/block
#     type: DirectoryOrCreate

